"""add photos relationship

Revision ID: 5949ae0c90c7
Revises: 982041ed384e
Create Date: 2018-08-16 14:00:53.348350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5949ae0c90c7'
down_revision = '982041ed384e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('reviews', 'movie_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('movie_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'image_path')
    # ### end Alembic commands ###
