"""add photos relationship

Revision ID: 982041ed384e
Revises: d0df93315629
Create Date: 2018-08-16 13:58:25.438980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982041ed384e'
down_revision = 'd0df93315629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('movie_path', sa.String(), nullable=True))
    op.drop_column('reviews', 'image_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'movie_path')
    # ### end Alembic commands ###
